spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:4306/construction-map?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        batch_fetch_style: dynamic
    open-in-view: false # true